apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dtns
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dtns
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dtns
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dtns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dtns
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-alzd-tenant/rhtap-demo-app/hacbs-test-project-dtns@sha256:e7ea70c082237203430d9b9254dd320ddf1ee0272d6ae46de341d52a5c80ed9e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
